version: '3.4'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh
    command: sleep infinity
    user: 1000:1000
    env_file:
      - .env

  back:
    restart: unless-stopped
    networks:
      - default
    build:
      context: ..
      dockerfile: dev/Dockerfile.back
      # dockerfile: ./Dockerfile
    command:
      - '/scripts/entrypoint.dev.sh'
    volumes:
      - ..:/app
    # depends_on:
    #   - mongo
    environment:
      - NODE_ENV=localhost
    ports:
      - 8080:8080
    env_file:
      - .env

  # mongo:
  #   image: mongo:4.2.8-bionic
  #   command: ['--replSet', 'rs0', '--bind_ip_all']
  #   hostname: mongo
  #   container_name: mongo
  #   restart: always
  #   healthcheck:
  #     test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
  #     interval: 10s
  #     start_period: 30s
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /data/db:/data/db

  # web:
  #   restart: always
  #   build:
  #     context: ../docker/nginx
  #     dockerfile: Dockerfile
  #   environment:
  #     DOLLAR: '$$'
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  #   ports:
  #     - 80:80

networks:
  default:
    driver: bridge
